# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reflekto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reflekto
  pod 'RxSwift', '~> 3.4'
  pod 'RxCocoa', '~> 3.4'
  pod 'Google/SignIn'
  pod 'GoogleAPIClientForREST/Gmail'

end
