# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def common_pods
    # Pods for reflekto
    pod 'RxSwift', '~> 3.4'
    pod 'RxCocoa', '~> 3.4'
    pod 'Google/SignIn'
    pod 'GoogleAPIClientForREST/Gmail'
end

target 'reflekto' do
    common_pods
end

target 'reflektoTests' do
    common_pods
end
